telegram:
  username: "manicure-scheduler-bot"
  bot-token: ${MANICURE_SCHEDULER_TELEGRAM_BOT_TOKEN}

spring:
  datasource:
    url: ${MANICURE_SCHEDULER_CONNECTION_STRING}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: "classpath:migration"

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
