telegram:
  username: "manicure-scheduler-bot"
  bot-token: ${APP_TELEGRAM_BOT_TOKEN}
  time-picker-url: ${APP_TIME_PICKER_URL}

spring:
  datasource:
    url: ${APP_DATABASE_CONNECTION_STRING}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: "classpath:migration"

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false

  jackson:
    property-naming-strategy: SNAKE_CASE
