CREATE TABLE clients
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    telegram_id   BIGINT                                  NOT NULL,
    full_name     VARCHAR(255)                            NOT NULL,
    phone_number  VARCHAR(255)                            NOT NULL,
    manicure_type VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_clients PRIMARY KEY (id)
);

CREATE TABLE manicurists
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name      VARCHAR(255)                            NOT NULL,
    portfolio_link VARCHAR(255),
    CONSTRAINT pk_manicurists PRIMARY KEY (id)
);

CREATE TABLE events
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    time_from  TIMESTAMP WITHOUT TIME ZONE,
    time_to    TIMESTAMP WITHOUT TIME ZONE,
    manicurist BIGINT,
    client     BIGINT                                  NOT NULL,
    CONSTRAINT pk_events PRIMARY KEY (id)
);

CREATE TABLE manicures
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255)                            NOT NULL,
    price           INTEGER                                 NOT NULL,
    currency        VARCHAR(255)                            NOT NULL,
    duration_in_min INTEGER                                 NOT NULL,
    CONSTRAINT pk_manicure_types PRIMARY KEY (id)
);

CREATE TABLE schedule_weekends
(
    schedule_id BIGINT NOT NULL,
    weekend_day VARCHAR(255)
);

CREATE TABLE schedules
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    schedule_types     VARCHAR(255),
    start_working_time time WITHOUT TIME ZONE                  NOT NULL,
    end_working_time   time WITHOUT TIME ZONE                  NOT NULL,
    CONSTRAINT pk_schedules PRIMARY KEY (id)
);

CREATE TABLE manicurists_schedules
(
    manicurist_entity_id BIGINT NOT NULL,
    schedules_id         BIGINT NOT NULL
);

CREATE TABLE schedule_manicurist
(
    manicurist_id BIGINT NOT NULL,
    schedule_id   BIGINT NOT NULL
);

ALTER TABLE schedule_weekends
    ADD CONSTRAINT fk_schedule_weekends_on_schedule_entity FOREIGN KEY (schedule_id) REFERENCES schedules (id);

ALTER TABLE schedule_manicurist
    ADD CONSTRAINT fk_schman_on_manicurist_entity FOREIGN KEY (manicurist_id) REFERENCES manicurists (id);

ALTER TABLE schedule_manicurist
    ADD CONSTRAINT fk_schman_on_schedule_entity FOREIGN KEY (schedule_id) REFERENCES schedules (id);

ALTER TABLE manicurists_schedules
    ADD CONSTRAINT fk_mansch_on_manicurist_entity FOREIGN KEY (manicurist_entity_id) REFERENCES manicurists (id);

ALTER TABLE manicurists_schedules
    ADD CONSTRAINT fk_mansch_on_schedule_entity FOREIGN KEY (schedules_id) REFERENCES schedules (id);

ALTER TABLE clients
    ADD CONSTRAINT uc_clients_telegram UNIQUE (telegram_id);

ALTER TABLE events
    ADD CONSTRAINT FK_EVENTS_ON_CLIENT FOREIGN KEY (client) REFERENCES clients (telegram_id);

ALTER TABLE events
    ADD CONSTRAINT FK_EVENTS_ON_MANICURIST FOREIGN KEY (manicurist) REFERENCES manicurists (id);
